import Head from "next/head";
import Link from "next/link";
import data from "data";
import Posts from "components/Posts";
import AboutmeSidebar from "components/AboutmeSidebar";
import RecentpostsSidebar from "components/RecentpostsSidebar";

export default function index() {
  const cards = data
    .filter((item) => item.id !== 1)
    .map((item) => {
      return (
        <Posts
          key={item.id}
          image={item.image}
          title={item.title}
          date={item.date}
          text={item.text}
        />
      );
    });

  return (
    <>
      <Head>
        <title>Module 2 - A simple life</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="mx-auto w-[90%] max-w-[980px] py-8">
        <div className="flex flex-col gap-10 md:flex-row">
          <main className="md:w-[75%]">
            <div className="flex flex-col justify-between">
              <h2 className="order-1 font-lora text-2xl font-medium text-sky-900 md:order-4 md:my-3">
                Finding simplicity in life
              </h2>
              <img
                src="/life.jpg"
                alt="a clock, pot of plant and table lamp"
                className="order-2 my-4 min-h-[250px] max-w-full md:mb-4 md:mt-0"
              />
              <p className="order-3 mb-2 text-sm">July 23, 2019 | 3 comments</p>
              <p className="order-4 leading-relaxed">
                <strong className="text-neutral-700">
                  Life can get complicated really quickly
                </strong>
                , but it doesn't have to be! There are many ways to simplify
                your life,{" "}
                <Link
                  href="#"
                  className="text-sky-600 underline hover:text-sky-900"
                >
                  a few of which we've explored in the past
                </Link>
                . This week we're taking a bit of a approach though, in how you
                can find simplicity in the life you already living.
              </p>
              <Link
                href="#"
                className="order-5 my-6 font-bold uppercase text-sky-600 hover:text-sky-900"
              >
                continue reading
              </Link>
            </div>
            <div className="mb-10 border-b-4 border-neutral-200" />
            <div className="flex flex-col gap-4 md:gap-8">{cards}</div>
          </main>
          <div className="md:w-[25%]">
            <AboutmeSidebar />
            <RecentpostsSidebar />
          </div>
        </div>
      </div>
    </>
  );
}
