import Head from "next/head";
import data from "data";
import Posts from "components/Posts";
import AboutmeSidebar from "components/AboutmeSidebar";
import RecentpostsSidebar from "components/RecentpostsSidebar";

export default function RecentPosts() {
  const cards = data.map((item) => {
    return (
      <Posts
        key={item.id}
        image={item.image}
        title={item.title}
        date={item.date}
        text={item.text}
      />
    );
  });

  return (
    <>
      <Head>
        <title>Module 2 - A simple life</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="mx-auto w-[90%] max-w-[980px] py-8">
        <div className="flex flex-col gap-10 md:flex-row">
          <main className="md:w-[75%]">{cards}</main>
          <div className="md:w-[25%]">
            <AboutmeSidebar />
            <RecentpostsSidebar />
          </div>
        </div>
      </div>
    </>
  );
}
